# Generated by Django 5.1.2 on 2024-11-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('celular', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('correo', models.CharField(max_length=254, verbose_name='Correo Eletronico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Nacimiento')),
            ],
        ),
    ]
